import { useState } from 'react';
import { Button, FormInput, SearchInput } from '../common/FormElements';

const HumanResources = () => {
  const [attendance, setAttendance] = useState([]);
  const [salary, setSalary] = useState([]);
  const [searchAttendance, setSearchAttendance] = useState('');
  const [searchSalary, setSearchSalary] = useState('');

  const filteredAttendance = attendance.filter(a =>
    a.member.toLowerCase().includes(searchAttendance.toLowerCase())
  );

  const filteredSalary = salary.filter(s =>
    s.member.toLowerCase().includes(searchSalary.toLowerCase())
  );

  return (
    <div className="p-6 space-y-12">
      {/* Attendance Section */}
      <section>
        <h2 className="text-xl font-bold text-gray-800 mb-4">Attendance</h2>
        <div className="bg-white p-6 rounded-xl shadow border">
          <h3 className="text-lg font-semibold mb-4">Add an Attendance</h3>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
            <FormInput label="Member" placeholder="Member Name" />
            <FormInput label="Date" type="date" />
            <FormInput label="Sign In" type="time" />
          </div>
          <div className="flex space-x-2">
            <Button variant="primary">Save Information</Button>
            <Button variant="danger">Cancel</Button>
          </div>
        </div>

        <div className="bg-white mt-6 p-6 rounded-xl shadow border">
          <h3 className="text-lg font-semibold mb-4">Attendance List</h3>
          <SearchInput
            placeholder="Search attendance..."
            value={searchAttendance}
            onChange={(e) => setSearchAttendance(e.target.value)}
          />
          <table className="w-full mt-4 text-sm text-gray-700">
            <thead className="bg-gray-50">
              <tr>
                <th className="p-3 text-left">Member</th>
                <th>Date</th>
                <th>Sign In</th>
                <th>Sign Out</th>
                <th>Stay Time</th>
              </tr>
            </thead>
            <tbody>
              {filteredAttendance.map((a, index) => (
                <tr key={index} className="border-b">
                  <td className="p-3">{a.member}</td>
                  <td>{a.date}</td>
                  <td>{a.signIn}</td>
                  <td>{a.signOut}</td>
                  <td>
                    <span className="px-2 py-1 rounded-full text-xs bg-purple-100 text-purple-800">
                      {a.stayTime}
                    </span>
                  </td>
                </tr>
              ))}
              {filteredAttendance.length === 0 && (
                <tr>
                  <td colSpan="5" className="text-center text-gray-500 py-4">
                    No records found.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </section>

      {/* Salary Section */}
      <section>
        <h2 className="text-xl font-bold text-gray-800 mb-4">Salary</h2>
        <div className="bg-white p-6 rounded-xl shadow border">
          <h3 className="text-lg font-semibold mb-4">Add a Salary</h3>
          <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-6">
            <FormInput label="Member" placeholder="Member Name" />
            <FormInput label="Date" type="date" />
            <FormInput label="Total Salary" placeholder="Salary Amount" />
            <FormInput label="Working Days" placeholder="Working Days" />
          </div>
          <div className="flex space-x-2">
            <Button variant="primary">Save Information</Button>
            <Button variant="danger">Cancel</Button>
          </div>
        </div>

        <div className="bg-white mt-6 p-6 rounded-xl shadow border">
          <h3 className="text-lg font-semibold mb-4">Salary List</h3>
          <SearchInput
            placeholder="Search salary records..."
            value={searchSalary}
            onChange={(e) => setSearchSalary(e.target.value)}
          />
          <table className="w-full mt-4 text-sm text-gray-700">
            <thead className="bg-gray-50">
              <tr>
                <th className="p-3 text-left">Member</th>
                <th>Date</th>
                <th>Total Salary</th>
                <th>Working Days</th>
                <th>Generated By</th>
                <th>Status</th>
              </tr>
            </thead>
            <tbody>
              {filteredSalary.map((s, index) => (
                <tr key={index} className="border-b">
                  <td className="p-3">{s.member}</td>
                  <td>{s.date}</td>
                  <td>{s.amount}</td>
                  <td>
                    <span className="px-2 py-1 rounded-full text-xs bg-blue-100 text-blue-800">
                      {s.workingDays} Days
                    </span>
                  </td>
                  <td>{s.generatedBy}</td>
                  <td>
                    <span className={`px-2 py-1 rounded-full text-xs ${
                      s.status === 'Paid' ? 'bg-green-100 text-green-700' : 'bg-red-100 text-red-700'
                    }`}>
                      {s.status}
                    </span>
                  </td>
                </tr>
              ))}
              {filteredSalary.length === 0 && (
                <tr>
                  <td colSpan="6" className="text-center text-gray-500 py-4">
                    No salary data found.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </section>
    </div>
  );
};

export default HumanResources;
